services:
  election-app:
    build:
      context: ./src/election-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - election-service

  election-service:
    build:
      context: ./src/election-service
      dockerfile: Dockerfile
    ports:
      - "5127:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - election-service-data:/app

volumes:
  election-service-data: