@election_service_HostAddress = http://localhost:5127

GET {{election_service_HostAddress}}/weatherforecast/
Accept: application/json

###

# Register a new voter
POST {{election_service_HostAddress}}/api/voter
Content-Type: application/json

{
  "name": "nathan Gurung",
  "email": "john.doe@example.com",
  "firstName": "Nathan",
  "middleName": "B",
  "lastName": "Gurung",
  "address": "123 Main St",
  "city": "Springfield",
  "state": "IL",
  "zipCode": "62701",
  "phoneNumber": "120-555-1234",
  "referredBy": "Bindu Gurung"
}

###

# Get all registered voters
GET {{election_service_HostAddress}}/api/voter
Accept: application/json

###

# Get a specific voter by ID
GET {{election_service_HostAddress}}/api/voter/1
Accept: application/json